### ISSUE TITLE
P2SH address support

### ISSUE THREAD

**Issue by mifunetoshiro** [prusnak/bip32utils#14]
```
def SegWitP2SHAddress(self):
    addressversion = b'\x05' if not self.testnet else b'\xc4'
    scripthash = hashlib.new('ripemd160', hashlib.sha256(b'\x00\x14' + self.Identifier()).digest()).digest()
    return Base58.check_encode(addressversion + scripthash)
```

Taken from [Reddit](https://www.reddit.com/r/Bitcoin/comments/6xz9b3/new_python_bitcoin_library_released_have_fun/dmk6e5x/)

I guess Bech32 support should also be added eventually.

**Comment by prusnak** [comment]
Please send a pull request and close this issue. Thanks!
